CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE subscriptions (
    subscription_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE users_subscriptions (
    user_id bigint REFERENCES users(user_id) ON DELETE CASCADE,
    subscription_id bigint REFERENCES subscriptions(subscription_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, subscription_id)
);

INSERT INTO users (name) VALUES
    ('Alice'),
    ('Bob'),
    ('Charlie'),
    ('David'),
    ('Eve'),
    ('Frank'),
    ('Grace'),
    ('Hank'),
    ('Ivy'),
    ('Jack');

INSERT INTO subscriptions (name) VALUES
    ('Netflix'),
    ('YouTube Premium'),
    ('Spotify'),
    ('Amazon TV');

INSERT INTO users_subscriptions (user_id, subscription_id) VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (2, 4),
    (3, 1),
    (3, 2),
    (4, 1),
    (5, 1),
    (5, 2),
    (5, 4);